name: Deploy to Cloudflare Workers # gh secret set -f .env

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Run Database Migrations (D1)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: d1 migrations apply D1_DATABASE

      - name: Deploy to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          secrets: |
            CLERK_JWKS_ENDPOINT
            CLERK_JWT_ISSUER
            CLERK_SECRET_KEY
          postCommands: |
            echo "Deployment completed successfully!"
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_JWKS_ENDPOINT: ${{ secrets.CLERK_JWKS_ENDPOINT }}
          CLERK_JWT_ISSUER: ${{ secrets.CLERK_JWT_ISSUER }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      
      - name: Print Deployment URL
        run: echo "Deployed to ${{ steps.deploy.outputs.deployment-url }}" 